name: iOS CI
on:
  [push]
  # workflow_call:
  #   inputs:
  #     node-version:
  #       required: true
  #       type: string
  #     osx-version:
  #       required: true
  #       type: string

jobs:
  build:
    # runs-on: ${{ inputs.osx-version }}
    runs-on: macos-12
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v3

      - name: Run buildcache
        uses: mikehardy/buildcache-action@v2.1.0

      # continue-on-error: true

      # - name: Setup Node environment v. ${{ inputs.node-version }}
      - name: Setup Node environment v. '16'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          # node-version: ${{ inputs.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci

      # for debugging runners
      # - name: react native info
      #   run: npx react-native info

      - name: Cache pods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - name: Install pod dependencies
        working-directory: ios
        run: pod install

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build App
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace ios/TestProject.xcworkspace \
          -scheme TestProject \
          -sdk iphonesimulator \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"

      # - name: Compress .xcarchive
      #   run: zip -r -9 TestProject.xcarchive.zip $PWD/TestProject.xcarchive/

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: ios-xarchive
      #     path: TestProject.xcarchive.zip
