name: iOS CI
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      osx-version:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      node-version:
        description: Specify Node version
        required: true
        type: string
        options:
        - '16'
      osx-version:
        description: Specify OSX version
        required: true
        type: string
        options:
        - macos-12
        - macos-latest

jobs:
  build:
    runs-on: ${{ inputs.osx-version }}
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v3

      - name: Run buildcache
        uses: mikehardy/buildcache-action@v2.1.0

      - name: Setup Node environment v. ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci

      # for debugging runners
      # - name: react native info
      #   run: npx react-native info

      - name: Cache pods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - name: Install pod dependencies
        working-directory: ios
        run: pod install

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build App (Debug)
        working-directory: ios
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace TestProject.xcworkspace \
          -scheme TestProject \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
