name: Run CI
description: 'Runs a full CI, including: js tests, Android- andd iOS build.'
run-name: ${{ github.actor }} - Running full CI
on: [push]
# on:
#   pull_request:
#     # only run when running pr against main
#     branches:
#       - main

env:
  NODE_VERSION: '16'
  UBUNTU_VERSION: 'ubuntu-22.04'
  OSX_VERSION: 'macos-12'

jobs:
  steps:
  - name: Set env variables
    run: |
      echo "NODE_VERSION=16" >> $GITHUB_ENV && \
      echo "UBUNTU_VERSION=ubuntu-22.04" >> $GITHUB_ENV && \
      echo "OSX_VERSION=macos-12" >> $GITHUB_ENV

    - name: run-react-native-tests:
      uses: ./.github/workflows/npm.yml
      with:
        node-version: ${{ env.NODE_VERSION }}
        ubuntu-version: ${{ env.UBUNTU_VERSION }}

    - name: run-android-build:
      needs: run-react-native-tests
      uses: ./.github/workflows/android.yml
      with:
        node-version: ${{ env.NODE_VERSION }}
        ubuntu-version: ${{ env.UBUNTU_VERSION }}

    - name: run-ios-build:
      needs: run-android-build
      uses: ./.github/workflows/ios.yml
      with:
        node-version: ${{ env.NODE_VERSION }}
        osx-version: ${{ env.OSX_VERSION }}
