name: Run full CI
run-name: ${{ github.actor }} - Run full CI
on: [push]
# on:
#   pull_request:
#     # only run when running pr against main
#     branches:
#       - main
# TODO: find a way to set global env vars so we don't have to specify versions foreach workflow

jobs:
  run-react-native-tests:
    uses: ./.github/workflows/npm.yml
    with:
      node-version: '16'
      ubuntu-version: ubuntu-22.04
  run-android-build:
    needs: run-react-native-tests
    uses: ./.github/workflows/android.yml
    with:
      node-version: '16'
      ubuntu-version: ubuntu-22.04
  run-ios-build:
    needs: run-android-build
    uses: ./.github/workflows/ios.yml
    with:
      node-version: '16'
      osx-version: macos-12
